modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

issueTrackerURL="https://github.com/kyrptonaught/customportalapi/issues" #optional

[[mods]] #mandatory

modId="customportalapi" #mandatory

version="0.0.1-beta50-1.18-forge" #mandatory

displayName="Custom Portal Api [Forge]" #mandatory

displayURL="https://github.com/kyrptonaught/customportalapi" #optional

logoFile="icon.png" #optional

credits="kyrptonaught (main author of the fabric version), Waterpicker (for the forge port) ,Mysticpasta1 (for the forge toml)" #optional

authors="kyrptonaught, Waterpicker" #optional

description='''
Create portals out of anything!
'''

[[dependencies.customportalapi]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.customportalapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"